(()=>{'use strict';
const $=id=>document.getElementById(id);
const els={board:$('board'),canvas:$('gameCanvas'),overlay:$('overlay'),title:$('modalTitle'),modalText:$('modalText'),eyebrow:$('modalEyebrow'),actions:$('modalActions'),illustration:$('modalIllustration'),ready:$('readyPreview'),next:$('nextPreview'),score:$('score'),time:$('time'),level:$('levelLabel'),combo:$('comboValue'),progress:$('progressText'),mission:$('missionText'),bar:$('timebar'),boss:$('bossInfo'),bossName:$('bossName'),bossStatus:$('bossStatus'),hp:$('hpFill'),snap:$('snapWrap'),toast:$('comboToast'),comboTitle:$('comboTitle'),comboDesc:$('comboDesc'),tip:$('tutorialTip'),hint:$('hintLine'),error:$('errorBox')};
const ctx=els.canvas.getContext('2d');
const COLORS=['#ff73b6','#52cdf7','#a98aff','#58dfb6','#ffc267'];
const LEVELS=[
{name:"Snap's First Mission",time:150,colors:3,rows:['000111222','000111222'],objective:'Learn to match 3 bubbles'},
{name:'Coral Reef Passage',time:145,colors:3,rows:['000111222','000111222','00.11.22.'],objective:'Use Swap to plan your shots'},
{name:'The Pearl Maze',time:140,colors:3,rows:['001122001','001122001','..11.22..'],objective:'Use a wall bounce to reach the pearls'},
{name:'Jellyfish Guardian',time:165,colors:3,boss:'jelly',hp:3,objective:'Pop the shield, then strike the jellyfish'},
{name:'Whispering Reef',time:150,colors:4,rows:['001122330','001122330','..11.22..','...1.2...'],objective:'Drop bubbles by cutting their supports'},
{name:'Sunken Gate',time:155,colors:4,rows:['001122330','001122330','00.11.22.','....33...'],seals:[[1,1],[1,6]],objective:'Release the two enchanted seals'},
{name:'Armored Crab Guardian',time:175,colors:4,boss:'crab',hp:4,objective:'Break the armor and hit the moving core'},
{name:'Crystal Passage',time:165,colors:4,rows:['001122330','001122330','0.1.2.3.0','..11.22..'],objective:'Clear the crystal-covered passage'},
{name:'Palace Entrance',time:175,colors:4,rows:['001122330','001122330','..112233.','...1122..'],seals:[[0,2],[0,5],[1,7]],objective:'Destroy the three palace locks'},
{name:'The Final Enchantment',time:210,colors:4,boss:'core',hp:5,objective:'Break the magical core to free Caspia'}];
const C=9,PI=Math.PI,SAVE='caspia-save-princess-v12-1',GUIDE='caspia-save-princess-guide-v12';
const DEFAULT={unlocked:1,stars:{},completed:false};
let progress=readSave(),state={mode:'story',level:1,quickStage:0,started:false,playing:false,paused:true,modal:true,grid:[],r:17,sx:34,sy:30,rows:12,w:360,h:480,offset:16,ready:0,next:1,shot:null,aim:{x:180,y:0},score:0,shots:0,streak:0,seconds:150,total:150,particles:[],floats:[],boss:null,seals:[],tutorial:'',comboUntil:0,shake:0};
let dpr=1,last=0,raf=0,pointerDown=false,soundEnabled=true,audio=null,currentDialog=null;
function readSave(){try{const s=JSON.parse(localStorage.getItem(SAVE)||'null');return s&&typeof s==='object'?{...DEFAULT,...s,stars:s.stars||{}}:{...DEFAULT}}catch{return {...DEFAULT}}}
function store(){try{localStorage.setItem(SAVE,JSON.stringify(progress))}catch{}}
function setHint(text){els.hint.textContent=text}
let lastQuestState='';
function syncDesktopQuest(){
 const current=state.mode==='story'?state.level:0,completed=progress.unlocked;
 const tag=current+'|'+completed+'|'+state.mode;
 if(tag===lastQuestState)return;lastQuestState=tag;
 document.querySelectorAll('.quest-step').forEach(el=>{
  const n=Number(el.dataset.stage);
  el.classList.toggle('current',n===current);
  el.classList.toggle('done',n<completed&&n!==current);
 });
}

function setTip(text){els.tip.textContent=text;els.tip.hidden=!text}

const cine={box:$('cineBanner'),kicker:$('cineKicker'),heading:$('cineHeading'),caption:$('cineCaption'),flash:$('hitFlash')};
let cineTimer=0,chapterPending=false;
function sceneCaption(title,caption='',kicker='ROYAL RESCUE'){
 if(!state.started||state.modal||document.hidden)return;
 cine.heading.textContent=title;cine.caption.textContent=caption;cine.kicker.textContent=kicker;
 cine.box.classList.remove('show');void cine.box.offsetWidth;cine.box.classList.add('show');
 clearTimeout(cineTimer);cineTimer=setTimeout(()=>cine.box.classList.remove('show'),2080);
 if(soundEnabled&&kicker==='BOSS ENCOUNTER')sfx('stage');
}
function impact(kind='pop'){
 const cls=kind==='boss'?'boss-hit':'pop';cine.flash.classList.remove('pop','boss-hit');void cine.flash.offsetWidth;cine.flash.classList.add(cls);
 if(kind==='boss'){$('bossInfo').classList.remove('hit');void $('bossInfo').offsetWidth;$('bossInfo').classList.add('hit')}
 if(kind==='boss'&&navigator.vibrate)try{navigator.vibrate(35)}catch{}
}
function stampChapter(){const cfg=info();chapterPending=false;sceneCaption(cfg.boss?cfg.name:cfg.name,cfg.boss?'Clear the shields. Strike the glowing weak point!':cfg.objective,cfg.boss?'BOSS ENCOUNTER':'CHAPTER '+(state.mode==='quick'?state.quickStage+1:state.level));}

function sfx(kind){
 if(!soundEnabled)return;
 try{
  const AudioCtx=window.AudioContext||window.webkitAudioContext;if(!AudioCtx)return;
  audio=audio||new AudioCtx();if(audio.state==='suspended')audio.resume().catch(()=>{});
  const t0=audio.currentTime, notes={shoot:[330,220],pop:[520,740,990],swap:[490,740],hit:[230,155,110],win:[523,659,784,1047],danger:[330,220,140],click:[680],shield:[550,770,990],stage:[392,523,659]};
  (notes[kind]||notes.click).forEach((f,i)=>{const t=t0+i*(kind==='win'?.105:.045),dur=kind==='win'?.22:.12;
   const osc=audio.createOscillator(),gain=audio.createGain();osc.type=(kind==='hit'||kind==='danger')?'triangle':kind==='pop'?'sine':'sine';osc.frequency.setValueAtTime(f,t);osc.frequency.exponentialRampToValueAtTime(Math.max(70,f*(kind==='hit'?.65:kind==='shoot'?.55:1.16)),t+dur);
   gain.gain.setValueAtTime(.0001,t);gain.gain.exponentialRampToValueAtTime(.035,t+.012);gain.gain.exponentialRampToValueAtTime(.0001,t+dur);
   osc.connect(gain).connect(audio.destination);osc.start(t);osc.stop(t+dur+.015)
  });
  if(kind==='pop'||kind==='shoot'||kind==='hit'){
   const n=Math.min(2700,Math.round(audio.sampleRate*.045)),buf=audio.createBuffer(1,n,audio.sampleRate),ch=buf.getChannelData(0);
   for(let i=0;i<n;i++)ch[i]=(Math.random()*2-1)*Math.pow(1-i/n,2);
   const source=audio.createBufferSource(),filter=audio.createBiquadFilter(),gain=audio.createGain();source.buffer=buf;filter.type='lowpass';filter.frequency.value=kind==='hit'?750:kind==='shoot'?1300:2300;gain.gain.value=kind==='hit'?.085:.055;
   source.connect(filter).connect(gain).connect(audio.destination);source.start(t0);source.stop(t0+.045)
  }
 }catch(e){/* Audio is optional; game continues on restricted browsers. */}
}
function rand(seed){let a=seed>>>0;return()=>{a=(Math.imul(1664525,a)+1013904223)>>>0;return a/4294967296}}
function info(){return state.mode==='quick'?(state.quickStage===0?{name:'Quick Rescue: Clear the Reef',time:85,rows:['000111222','000111222'],colors:3,objective:'Clear the reef to reach Caspia'}:{name:'Quick Rescue: The Final Seal',time:105,boss:'core',hp:2,colors:3,objective:'Defeat the seal and save Caspia!'}):LEVELS[state.level-1]}
function fit(){const rect=els.board.getBoundingClientRect();if(rect.width<200||rect.height<200)throw new Error('Game board is not visible yet. Try Retry level.');state.w=Math.max(230,rect.width);state.h=Math.max(260,rect.height);dpr=Math.min(1.75,window.devicePixelRatio||1);els.canvas.width=Math.round(state.w*dpr);els.canvas.height=Math.round(state.h*dpr);ctx.setTransform(dpr,0,0,dpr,0,0);state.r=Math.min(18.5,(state.w-18)/(2*C+1));state.sx=state.r*2;state.sy=state.r*1.74;state.rows=Math.max(7,Math.min(15,Math.floor((state.h-111-state.r*2)/state.sy)+1));state.aim.x=state.w/2;state.aim.y=state.h*.25}
function loc(row,col){return{x:state.w/2-(C-1)*state.r+col*state.sx+(row%2)*state.r,y:state.offset+state.r+row*state.sy}}
function key(row,col){return row+','+col}
function inGrid(row,col){return row>=0&&row<state.rows&&col>=0&&col<C}
function adj(row,col){const m=row%2?[[0,-1],[0,1],[-1,0],[-1,1],[1,0],[1,1]]:[[0,-1],[0,1],[-1,-1],[-1,0],[1,-1],[1,0]];return m.map(([a,b])=>[row+a,col+b]).filter(([a,b])=>inGrid(a,b))}
function newGrid(){return Array.from({length:state.rows},()=>Array(C).fill(null))}
function loadPattern(rows){state.grid=newGrid();rows.slice(0,Math.min(rows.length,state.rows-2)).forEach((line,row)=>{for(let col=0;col<Math.min(C,line.length);col++){const n=line[col];state.grid[row][col]=n==='.'?null:Math.max(0,Math.min(COLORS.length-1,Number(n)||0))}})}
function shieldPattern(){const phase=state.boss?state.boss.max-state.boss.hp:0;const palettes=state.level===4||state.mode==='quick'?[0,1,2]:[0,1,2,3];const a=palettes[phase%palettes.length],b=palettes[(phase+1)%palettes.length];let rows=['.........','.........'];const shift=phase%2;rows[0]='.'+(a+'').repeat(3)+(b+'').repeat(3)+'..';rows[1]='..'+(a+'').repeat(2)+(b+'').repeat(2)+'...';if(shift)rows=rows.map(line=>line.slice(1)+'.');loadPattern(rows)}
function activeColors(){const n=new Set();for(const row of state.grid)for(const cell of row)if(cell!==null)n.add(cell);return [...n]}
function newBubble(){const colors=activeColors();if(!colors.length)return 0;return colors[Math.floor(Math.random()*colors.length)]}
function paintAmmo(){for(const [el,c] of [[els.ready,state.ready],[els.next,state.next]]){el.style.setProperty('--orb',c<0?'#f8e3ae':COLORS[c]||COLORS[0]);el.setAttribute('aria-label',c<0?'Pearl Strike':(['Pink','Blue','Purple','Green','Gold'][c]||'Bubble')+' bubble')}const pearl=state.boss&&state.boss.exposed;els.ready.parentElement.querySelector('b').textContent=pearl?'STRIKE':'READY';els.next.parentElement.querySelector('b').textContent=pearl?'STRIKE':'NEXT';$('swapBtn').disabled=!!state.shot||!!pearl||!state.playing||state.paused}
function updateHud(){const t=info();els.level.textContent=state.mode==='quick'?`Q${state.quickStage+1} / 2`:`${state.level} / 10`;els.score.textContent=state.score.toLocaleString();els.time.textContent=Math.floor(state.seconds/60)+':'+String(Math.ceil(state.seconds%60)).padStart(2,'0');els.combo.textContent='×'+Math.max(1,Math.min(5,state.streak));els.mission.textContent=t.objective;els.progress.textContent=state.mode==='quick'?'QUICK RESCUE':`Rescue ${Math.round((state.level-1)*100/10)}%`;els.bar.style.width=Math.max(0,100*state.seconds/state.total)+'%';document.querySelector('.timer-track').classList.toggle('danger',state.seconds<16);els.boss.hidden=!state.boss;if(state.boss){const b=state.boss;els.bossName.textContent=b.name;els.hp.style.width=(b.hp/b.max*100)+'%';els.bossStatus.textContent=b.exposed?'PEARL STRIKE! Aim for the glowing target':`Shielded • ${countGrid()} bubbles remain`}
  els.board.classList.toggle('boss-board',!!state.boss);syncDesktopQuest();paintAmmo()}
function countGrid(){let n=0;for(const row of state.grid)for(const c of row)if(c!==null)n++;return n}
function showError(e){state.paused=true;els.error.hidden=false;$('errorMessage').textContent=String(e&&e.message||e);console.error(e)}
function initialize(mode='story',level=1,quickStage=0){try{state.mode=mode;state.level=Math.min(10,Math.max(1,level));state.quickStage=quickStage;state.boss=null;state.seals=[];state.offset=info().boss?48:13;fit();const cfg=info();state.boss=cfg.boss?{type:cfg.boss,name:cfg.boss==='jelly'?'Jellyfish Guardian':cfg.boss==='crab'?'Armored Crab Guardian':'Enchanted Pearl Core',hp:cfg.hp,max:cfg.hp,exposed:false,pending:0,invulnerable:0}:null;
if(state.boss){shieldPattern()}else loadPattern(cfg.rows);
state.seals=(cfg.seals||[]).map(([r,c])=>({row:r,col:c,broken:false}));state.seconds=state.total=cfg.time;state.shot=null;state.score=0;state.shots=0;state.streak=0;state.particles=[];state.floats=[];state.comboUntil=0;els.toast.classList.remove('show');els.error.hidden=true;state.started=true;state.playing=true;state.paused=false;chapterPending=true;cine.box.classList.remove('show');state.ready=state.boss?newBubble():1;state.next=newBubble();els.rescuePreview=$('rescuePreview');els.rescuePreview.hidden=!(state.level>=9&&!state.boss&&state.mode==='story');setTip('');setHint('Drag to aim • Release to fire • Tap Swap to switch');updateHud();render();return true}catch(e){showError(e);return false}}
function getSiblingsColor(row,col,onlySame){const color=state.grid[row][col];const seen=new Set([key(row,col)]),stack=[[row,col]],out=[];while(stack.length){const [r,c]=stack.pop();out.push([r,c]);for(const [nr,nc] of adj(r,c)){const k=key(nr,nc);if(!seen.has(k)&&state.grid[nr][nc]!==null&&(!onlySame||state.grid[nr][nc]===color)){seen.add(k);stack.push([nr,nc])}}}return out}
function detach(){const seen=new Set(),stack=[];for(let c=0;c<C;c++)if(state.grid[0][c]!==null){seen.add(key(0,c));stack.push([0,c])}while(stack.length){const [r,c]=stack.pop();for(const [nr,nc] of adj(r,c)){const k=key(nr,nc);if(!seen.has(k)&&state.grid[nr][nc]!==null){seen.add(k);stack.push([nr,nc])}}}let dropped=0;for(let row=0;row<state.rows;row++)for(let col=0;col<C;col++)if(state.grid[row][col]!==null&&!seen.has(key(row,col))){popCell(row,col);dropped++}return dropped}
function popCell(row,col){const color=state.grid[row][col];if(color===null)return;const p=loc(row,col);particles(p.x,p.y,color,8);state.grid[row][col]=null;for(const seal of state.seals)if(seal.row===row&&seal.col===col&&!seal.broken){seal.broken=true;floating(p.x,p.y,'🔓', '#ffe6ae')}}
function particles(x,y,c,n=12){const r=rand(Math.floor(performance.now()*100+x+y));for(let i=0;i<n;i++){const angle=r()*PI*2,sp=40+r()*115;state.particles.push({x,y,vx:Math.cos(angle)*sp,vy:Math.sin(angle)*sp,life:.45+r()*.4,max:.85,size:2+r()*3,color:c})}if(state.particles.length>200)state.particles.splice(0,state.particles.length-200)}
function floating(x,y,text,color='#ffe18a'){state.floats.push({x,y,text,color,life:1.2})}
function applause(msg,desc){els.comboTitle.textContent=msg;els.comboDesc.textContent=desc;els.toast.classList.remove('show');void els.toast.offsetWidth;els.toast.classList.add('show');state.comboUntil=performance.now()+1200;els.snap.classList.remove('cheer');void els.snap.offsetWidth;els.snap.classList.add('cheer');sfx('pop')}
function launcher(){return{x:state.w/2,y:state.h-51}}
function nearestAttach(b,collided){const candidates=[];if(collided){for(const [row,col] of adj(collided[0],collided[1]))if(state.grid[row][col]===null){const p=loc(row,col);candidates.push({row,col,d:(p.x-b.x)**2+(p.y-b.y)**2})}}else{for(let col=0;col<C;col++)if(state.grid[0][col]===null){const p=loc(0,col);candidates.push({row:0,col,d:(p.x-b.x)**2+(p.y-b.y)**2})}}if(!candidates.length){for(let row=0;row<state.rows;row++)for(let col=0;col<C;col++)if(state.grid[row][col]===null){if(row>0&&!adj(row,col).some(([r,c])=>state.grid[r][c]!==null))continue;const p=loc(row,col);candidates.push({row,col,d:(p.x-b.x)**2+(p.y-b.y)**2})}}candidates.sort((a,b)=>a.d-b.d);return candidates[0]||null}
function land(b,collided){const p=nearestAttach(b,collided);state.shot=null;if(!p){lose('The reef is full.');return}state.grid[p.row][p.col]=b.color;const group=getSiblingsColor(p.row,p.col,true);if(group.length>=3){for(const [r,c] of group)popCell(r,c);const fallen=detach();state.streak++;const points=(group.length*20+fallen*25)*Math.min(5,state.streak);state.score+=points;floating(b.x,b.y,'+'+points);impact('pop');applause(state.streak>=5?'LEGENDARY!':state.streak>=3?'FANTASTIC!':state.streak===2?'AMAZING!':'GREAT!',`${group.length+fallen} pearls cleared!`)}else state.streak=0;
state.shots++;if(!countGrid()){if(state.boss){state.boss.exposed=true;state.ready=-1;state.next=-1;setHint('SHIELD BROKEN! Shoot the glowing weak point!');sceneCaption('PEARL STRIKE!','Aim for the glowing weak point','SHIELD BROKEN');sfx('shield')}else{finish(true);return}}
if(state.grid.slice(Math.max(0,state.rows-2)).some(row=>row.some(x=>x!==null))){lose('The bubbles reached Snap.');return}
if(!state.boss&&state.shots%Math.max(6,11-Math.floor(state.level/3))===0){addRow()}
if(!state.boss||!state.boss.exposed){state.ready=activeColors().includes(state.next)?state.next:newBubble();state.next=newBubble()}
if(state.tutorial==='shoot'){state.tutorial='swap';setTip('GOOD! Now tap SWAP below to change the loaded bubble.');setHint('Try the Swap button to finish your training')}updateHud()}
function addRow(){if(state.grid[state.rows-1].some(x=>x!==null)){lose('The reef reached Snap.');return}for(let i=state.rows-1;i>0;i--)state.grid[i]=state.grid[i-1].slice();const r=rand(state.level*1234+state.shots*13);const list=activeColors();state.grid[0]=Array.from({length:C},()=>list[Math.floor(r()*list.length)]??0);setHint('The current is bringing more enchanted bubbles!')}
function damageBoss(){const b=state.boss;if(!b||!b.exposed||b.invulnerable>0)return;state.shot=null;b.hp--;b.invulnerable=.45;state.shots++;state.streak++;state.score+=250*Math.max(1,state.streak);particles(weakPoint().x,weakPoint().y,4,35);floating(weakPoint().x,weakPoint().y,'-1 HP • +'+(250*Math.max(1,state.streak)),'#ffdf91');sfx('hit');impact('boss');state.shake=.24;applause(b.hp===0?'LEGENDARY!':'DIRECT HIT!','The guardian is weakening!');if(b.hp<=0){updateHud();finish(true);return}b.exposed=false;b.pending=.55;const palette=(state.level===4||state.mode==='quick')?[0,1,2]:[0,1,2,3];const phase=b.max-b.hp;state.ready=palette[phase%palette.length];state.next=palette[(phase+1)%palette.length];setHint('The boss rebuilt its shield! Break it again.');updateHud()}
function launch(){if(!state.playing||state.paused||state.shot||state.modal||state.boss?.pending>0)return;cine.box.classList.remove('show');clearTimeout(cineTimer);const o=launcher();let dx=state.aim.x-o.x,dy=Math.min(-state.r,state.aim.y-o.y),l=Math.hypot(dx,dy)||1;dx/=l;dy/=l;state.shot={x:o.x,y:o.y,vx:dx*610,vy:dy*610,color:state.ready,kind:state.boss&&state.boss.exposed?'pearl':'bubble',targetX:state.boss&&state.boss.exposed?weakPoint().x:null};els.snap.classList.remove('fire');void els.snap.offsetWidth;els.snap.classList.add('fire');sfx('shoot');paintAmmo()}
function step(dt){if(!state.playing||state.paused||state.modal)return;state.seconds=Math.max(0,state.seconds-dt);if(state.seconds<=0){lose('Time ran out!');return}if(state.boss){if(state.boss.pending>0){state.boss.pending-=dt;if(state.boss.pending<=0)shieldPattern()}state.boss.invulnerable=Math.max(0,state.boss.invulnerable-dt)}if(state.shot){const b=state.shot;const sub=Math.ceil(610*dt/Math.max(3,state.r*.3));for(let i=0;i<sub&&state.shot;i++){const t=dt/sub;b.x+=b.vx*t;b.y+=b.vy*t;if(b.x<=state.r){b.x=state.r;b.vx=Math.abs(b.vx);sfxWall()}if(b.x>=state.w-state.r){b.x=state.w-state.r;b.vx=-Math.abs(b.vx);sfxWall()}
if(b.kind==='pearl'){const c=weakPoint();if(Math.hypot(b.x-c.x,b.y-c.y)<state.r*1.25+16){damageBoss();break}if(b.y<2){state.shot=null;state.shots++;setHint('Missed! Aim for the glowing boss core.');break}}
else{let collided=null;if(b.y<=state.offset+state.r){land(b,null);break}scan:for(let row=0;row<state.rows;row++)for(let col=0;col<C;col++)if(state.grid[row][col]!==null){const q=loc(row,col);if(Math.hypot(b.x-q.x,b.y-q.y)<state.r*1.85){collided=[row,col];break scan}}if(collided){land(b,collided);break}}}}
for(const p of state.particles){p.life-=dt;p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=60*dt}state.particles=state.particles.filter(p=>p.life>0);for(const f of state.floats){f.life-=dt;f.y-=32*dt}state.floats=state.floats.filter(f=>f.life>0);state.shake=Math.max(0,state.shake-dt);if(state.comboUntil&&performance.now()>state.comboUntil){state.comboUntil=0;els.toast.classList.remove('show')}hudElapsed+=dt;if(hudElapsed>.12){hudElapsed=0;updateHud()}}
let hudElapsed=0;let wallTime=0;function sfxWall(){const t=performance.now();if(t-wallTime>180){wallTime=t}}
function weakPoint(){const b=state.boss;const center=state.w/2;return{x:b&&b.type==='crab'?(state.shot?.kind==='pearl'?state.shot.targetX:center+(Math.floor(performance.now()/3600)%2?1:-1)*Math.min(46,state.w*.12)):center,y:Math.min(166,Math.max(115,state.h*.36))}}
const bubbleSprites=new Map();
function makeBubbleSprite(color){const cvs=document.createElement('canvas');cvs.width=cvs.height=108;const cc=cvs.getContext('2d');const x=54,y=54,size=47,col=color<0?'#ffe9b8':COLORS[color]||COLORS[0];const g=cc.createRadialGradient(36,34,2,x,y,size);g.addColorStop(0,'#fff');g.addColorStop(.25,col);g.addColorStop(.78,col);g.addColorStop(1,'#123653');cc.shadowBlur=13;cc.shadowColor=col;cc.fillStyle=g;cc.beginPath();cc.arc(x,y,size,0,PI*2);cc.fill();cc.shadowBlur=0;cc.strokeStyle='#d7fbffb5';cc.lineWidth=2;cc.stroke();cc.fillStyle='#ffffff91';cc.beginPath();cc.ellipse(39,35,12,5,-.5,0,PI*2);cc.fill();if(color===2){cc.strokeStyle='#ffffff9b';cc.lineWidth=2;cc.beginPath();cc.arc(54,54,9,0,PI*2);cc.stroke()}if(color===3){cc.fillStyle='#eaffff9c';cc.fillRect(50,50,8,8)}if(color===4||color<0){cc.strokeStyle='#ffffffbd';cc.lineWidth=2;cc.beginPath();cc.moveTo(54,45);cc.lineTo(63,54);cc.lineTo(54,63);cc.lineTo(45,54);cc.closePath();cc.stroke()}return cvs}
function orb(x,y,color,size=state.r){let sprite=bubbleSprites.get(color);if(!sprite){sprite=makeBubbleSprite(color);bubbleSprites.set(color,sprite)}ctx.drawImage(sprite,x-size*1.14,y-size*1.14,size*2.28,size*2.28)}
function bossDraw(){const b=state.boss;if(!b)return;const c=weakPoint(),x=state.w/2,y=c.y;ctx.save();ctx.translate(x,y);ctx.globalAlpha=b.pending>0?.5:1;
if(b.type==='jelly'){ctx.shadowColor='#da78fc';ctx.shadowBlur=22;ctx.fillStyle='#854dc4';ctx.strokeStyle='#f6b9ff';ctx.lineWidth=3;ctx.beginPath();ctx.arc(0,-5,43,PI,0);ctx.quadraticCurveTo(46,36,0,35);ctx.quadraticCurveTo(-46,36,-43,-5);ctx.fill();ctx.stroke();ctx.shadowBlur=0;ctx.strokeStyle='#d7a7ff';for(let i=-3;i<=3;i++){ctx.beginPath();ctx.moveTo(i*10,33);ctx.quadraticCurveTo(i*9-9,52,i*11,66);ctx.stroke()}ctx.fillStyle='#f8ebff';ctx.beginPath();ctx.arc(-13,5,5,0,PI*2);ctx.arc(13,5,5,0,PI*2);ctx.fill();ctx.fillStyle='#2a174d';ctx.beginPath();ctx.arc(-13,6,2,0,PI*2);ctx.arc(13,6,2,0,PI*2);ctx.fill()}
if(b.type==='crab'){ctx.fillStyle='#f97fa4';ctx.strokeStyle='#ffe1c7';ctx.lineWidth=4;ctx.beginPath();ctx.ellipse(0,12,42,30,0,0,PI*2);ctx.fill();ctx.stroke();ctx.strokeStyle='#ff9abd';ctx.lineWidth=7;for(const dir of [-1,1]){ctx.beginPath();ctx.moveTo(dir*30,4);ctx.lineTo(dir*59,-12);ctx.lineTo(dir*69,1);ctx.stroke();ctx.fillStyle='#ffb1bc';ctx.beginPath();ctx.arc(dir*70,-6,16,0,PI*2);ctx.fill();ctx.strokeStyle='#ffca9a';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(dir*48,25);ctx.lineTo(dir*60,37);ctx.moveTo(dir*42,35);ctx.lineTo(dir*55,46);ctx.stroke()}ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(-14,4,7,0,PI*2);ctx.arc(14,4,7,0,PI*2);ctx.fill();ctx.fillStyle='#25314b';ctx.beginPath();ctx.arc(-14,4,3,0,PI*2);ctx.arc(14,4,3,0,PI*2);ctx.fill()}
if(b.type==='core'){ctx.rotate(performance.now()/1700);for(let i=0;i<8;i++){const a=PI*2*i/8;ctx.beginPath();ctx.moveTo(Math.cos(a)*35,Math.sin(a)*35);ctx.lineTo(Math.cos(a+.22)*58,Math.sin(a+.22)*58);ctx.lineTo(Math.cos(a+.44)*35,Math.sin(a+.44)*35);ctx.closePath();ctx.fillStyle=i%2?'#7c70e9':'#bd7cee';ctx.fill()}ctx.rotate(-performance.now()/1700);ctx.fillStyle='#7851ce';ctx.strokeStyle='#e6bafa';ctx.lineWidth=4;ctx.beginPath();ctx.arc(0,0,38,0,PI*2);ctx.fill();ctx.stroke()}
ctx.restore();if(b.exposed){const glow=b.type==='crab'?weakPoint():{x,y};ctx.save();ctx.shadowColor='#ffe6a8';ctx.shadowBlur=24;ctx.strokeStyle='#fff1ad';ctx.lineWidth=4;ctx.beginPath();ctx.arc(glow.x,glow.y,16+Math.sin(performance.now()/150)*2,0,PI*2);ctx.stroke();ctx.fillStyle='#ffe39a';ctx.beginPath();ctx.arc(glow.x,glow.y,9,0,PI*2);ctx.fill();ctx.restore()}else{ctx.save();ctx.globalAlpha=.6;ctx.strokeStyle='#d49bfd';ctx.lineWidth=2;ctx.beginPath();ctx.arc(x,y,54+Math.sin(performance.now()/300)*2,0,PI*2);ctx.stroke();ctx.restore()}}
function traceAim(){if(state.shot||!state.playing)return;let o=launcher(),dx=state.aim.x-o.x,dy=Math.min(-state.r,state.aim.y-o.y),l=Math.hypot(dx,dy)||1,vx=dx/l,vy=dy/l,x=o.x,y=o.y;ctx.save();ctx.fillStyle='#b9f0f1a8';const spacing=22;for(let i=0;i<24;i++){x+=vx*spacing;y+=vy*spacing;if(x<state.r){x=2*state.r-x;vx=Math.abs(vx)}if(x>state.w-state.r){x=2*(state.w-state.r)-x;vx=-Math.abs(vx)}if(y<state.r+state.offset||y<10)break;if(state.shot)break;ctx.beginPath();ctx.arc(x,y,Math.max(1.4,2.2-i*.025),0,PI*2);ctx.fill()}ctx.restore()}
function render(){ctx.clearRect(0,0,state.w,state.h);if(state.shake>0){ctx.save();ctx.translate(Math.sin(performance.now()/25)*state.shake*9,0)}ctx.save();if(state.boss)bossDraw();for(let row=0;row<state.rows;row++)for(let col=0;col<C;col++)if(state.grid[row][col]!==null){const p=loc(row,col);orb(p.x,p.y,state.grid[row][col])}for(const seal of state.seals)if(!seal.broken&&state.grid[seal.row]&&state.grid[seal.row][seal.col]!==null){const q=loc(seal.row,seal.col);ctx.fillStyle='#ffdb91';ctx.font=`${state.r}px sans-serif`;ctx.textAlign='center';ctx.fillText('♙',q.x,q.y+state.r*.37)}if(state.playing&&!state.paused){traceAim();if(!state.shot){const o=launcher();orb(o.x,o.y,state.ready,state.r*.75)}}if(state.shot)orb(state.shot.x,state.shot.y,state.shot.color,state.r*.8);ctx.restore();for(const p of state.particles){ctx.globalAlpha=Math.min(1,p.life*1.3);ctx.fillStyle=COLORS[p.color]||'#ffe3ae';ctx.beginPath();ctx.arc(p.x,p.y,p.size,0,PI*2);ctx.fill()}ctx.globalAlpha=1;for(const f of state.floats){ctx.globalAlpha=Math.min(1,f.life);ctx.font='bold 14px system-ui';ctx.textAlign='center';ctx.fillStyle=f.color;ctx.fillText(f.text,f.x,f.y)}ctx.globalAlpha=1;if(state.shake>0)ctx.restore()}
function makeButton(text,fn,kind=''){const b=document.createElement('button');b.textContent=text;b.className=kind;b.addEventListener('click',()=>{sfx('click');fn()});return b}
function dialog({eyebrow='ROYAL MISSION',title,text='',buttons=[],picture='',html=''}){state.modal=true;state.paused=true;currentDialog={eyebrow,title,text,buttons,picture,html};els.eyebrow.textContent=eyebrow;els.title.textContent=title;els.modalText.textContent=text;els.illustration.innerHTML='';els.illustration.hidden=!(picture||html);if(picture){const img=document.createElement('img');img.src=picture;img.alt='Princess Caspia';els.illustration.appendChild(img)}if(html)els.illustration.innerHTML=html;els.actions.replaceChildren(...buttons.map(v=>makeButton(v.label,v.action,v.kind||'')));els.overlay.hidden=false}
function closeDialog(){state.modal=false;state.paused=false;els.overlay.hidden=true;els.overlay.classList.remove('final-rescue');last=performance.now();updateHud();if(chapterPending)stampChapter()}
function ask(title,text,doIt,back){dialog({eyebrow:'PLEASE CONFIRM',title,text,buttons:[{label:'Cancel',action:()=>{if(back)back();else closeDialog()}},{label:'Confirm',kind:'warn',action:()=>{closeDialog();doIt()}}]})}
function pauseDialog(){dialog({eyebrow:'GAME PAUSED',title:'Take a breath, Guardian',text:'Your timer is paused. All unlocked stages stay saved.',buttons:[{label:'Resume',kind:'primary',action:closeDialog},{label:'Guide',action:()=>guide(true)},{label:'Levels',action:levelMap},{label:'Restart',action:()=>ask('Restart this level?','The current round will restart.',()=>resetLevel(),pauseDialog)},{label:'Home',action:()=>ask('Return to the portal?','Your unlocked levels will remain saved.',()=>location.href='index.html',pauseDialog)},{label:'Quit',kind:'warn',action:()=>ask('Quit Rescue?', 'Your unlocked levels and earned stars will stay saved.',()=>location.href='index.html',pauseDialog)}]})}
function resetLevel(){initialize(state.mode,state.level,state.quickStage);if(state.tutorial){state.tutorial='';setTip('')}closeDialog()}
function enterStage(mode,level,quickStage=0){initialize(mode,level,quickStage);if(!state.boss){closeDialog();return}const boss=state.boss;const descriptions={jelly:'The Jellyfish Guardian protects the first passage. Clear its shield and fire glowing Pearl Strikes at its center.',crab:'The Armored Crab blocks the palace. Break its shield, then strike its moving weak point.',core:'Caspia is behind the Enchanted Pearl Core! Pop the shield and destroy the core—never aim at Caspia.'};dialog({eyebrow:'BOSS ENCOUNTER',title:boss.name,text:descriptions[boss.type],buttons:[{label:'Begin Battle!',kind:'primary',action:closeDialog},{label:'Level Map',action:levelMap}]})}
function victoryMessage(){if(state.mode==='quick')return state.quickStage?'Caspia is free! The enchanted pearl has shattered.':'The route is open! Time to break the final spell.';if(state.level===10)return 'The spell is broken! You saved Princess Caspia and restored her kingdom.';if(state.level===4)return 'The Jellyfish Guardian is defeated. Caspia feels the magic weakening!';if(state.level===7)return 'The Armored Crab has fallen. The palace is within reach!';if(state.level===9)return 'The palace gates are open. Only the final spell remains.';return 'Snap is one step closer to rescuing Princess Caspia.'}
function finish(won){if(!state.playing)return;chapterPending=false;state.playing=false;state.paused=true;state.modal=true;const cfg=info(),elapsed=state.total-state.seconds;const stars=state.seconds>state.total*.62&&state.shots<=16?3:state.seconds>state.total*.23?2:1;const isFinal=state.mode==='quick'&&state.quickStage===1||state.mode==='story'&&state.level===10;const reached=state.level;if(won&&state.mode==='story'){progress.unlocked=Math.min(10,Math.max(progress.unlocked,state.level+1));progress.stars[state.level]=Math.max(progress.stars[state.level]||0,stars);if(isFinal)progress.completed=true;store()}sfx('win');const starText='★'.repeat(stars)+'☆'.repeat(3-stars);const buttons=isFinal?[{label:'Play Again',kind:'primary',action:()=>ask('Restart Adventure?', 'Start again at the beginning? Completed stages will remain unlocked.',()=>{initialize(state.mode,1,0);closeDialog()},()=>finishDialog())},{label:'Level Map',action:levelMap},{label:'Home',action:()=>ask('Return to the portal?','Your rescue has been saved.',()=>location.href='index.html',()=>finishDialog())},{label:'Quit',kind:'warn',action:()=>ask('Quit Game?', 'Your rescue achievement will remain saved.',()=>location.href='index.html',()=>finishDialog())}]:[{label:state.mode==='quick'?'Final Challenge →':`Level ${Math.min(10,state.level+1)} →`,kind:'primary',action:()=>{if(state.mode==='quick'){enterStage('quick',1,1)}else enterStage('story',Math.min(10,reached+1))}},{label:'Replay',action:()=>ask('Replay this level?','Restart this stage from the beginning.',()=>resetLevel(),()=>finishDialog())},{label:'Home',action:()=>ask('Go back to the portal?','Unlocked progress is saved.',()=>location.href='index.html',()=>finishDialog())},{label:'Quit',kind:'warn',action:()=>ask('Quit Game?', 'Your unlocked levels stay saved.',()=>location.href='index.html',()=>finishDialog())}];const isBonus=state.mode==='demo';if(isBonus){buttons.splice(0,buttons.length,{label:'Play Adventure',kind:'primary',action:()=>{initialize('story',progress.unlocked);closeDialog()}},{label:'Home',action:()=>location.href='index.html'})}
function finishDialog(){dialog({eyebrow:isFinal?'THE KINGDOM IS FREE!':'LEVEL COMPLETE',title:isFinal?'You Saved Princess Caspia!':'Congratulations!',text:victoryMessage()+` Score ${state.score.toLocaleString()} · ${state.shots} shots · ${Math.round(elapsed)}s played.`,picture:'assets/caspia.webp',html:'',buttons})}finishDialog();els.overlay.classList.toggle('final-rescue',isFinal);if(!isFinal)els.illustration.insertAdjacentHTML('afterbegin',`<div class="victory-stars" aria-label="${stars} stars">${starText}</div>`);else{els.illustration.insertAdjacentHTML('afterbegin','<div class="victory-stars">★★★</div>');}};
function lose(message){state.playing=false;state.paused=true;sfx('danger');dialog({eyebrow:'TRY AGAIN, GUARDIAN',title:'The Current Was Too Strong',text:message+' Snap can try again. Your unlocked levels are safe.',buttons:[{label:'Retry Level',kind:'primary',action:()=>resetLevel()},{label:'Level Map',action:levelMap},{label:'Home',action:()=>ask('Return home?','Your unlocked levels stay saved.',()=>location.href='index.html',()=>lose(message))}]})}
function levelMap(){const wasWelcome=els.title.textContent==='Save Princess Caspia';const container=document.createElement('div');container.className='level-map';LEVELS.forEach((v,i)=>{const n=i+1,b=makeButton(n+(v.boss?' 👑':''),()=>{if(n>progress.unlocked)return;enterStage('story',n)},(v.boss?'boss ':'')+(n>progress.unlocked?'locked ':'')+(n===state.level?'active':''));b.disabled=n>progress.unlocked;const tiny=document.createElement('small');tiny.textContent=n>progress.unlocked?'Locked':v.boss?'BOSS':(progress.stars[n]?'★'.repeat(progress.stars[n]):'Stage');b.appendChild(tiny);container.appendChild(b)});dialog({eyebrow:'THE UNDERWATER KINGDOM',title:'Choose Your Level',text:`${Math.min(10,progress.unlocked)} of 10 stages unlocked.`,buttons:[{label:'Back',action:()=>{if(wasWelcome||!state.playing)welcome();else pauseDialog() }},{label:'Quick Rescue',kind:'primary',action:()=>{initialize('quick',1,0);closeDialog()}}]});els.illustration.hidden=false;els.illustration.replaceChildren(container)}
function welcome(){const card='<div class="mode-cards"><button id="startAdventure"><span>🫧</span><strong>STORY ADVENTURE</strong><small>10 levels · 3 bosses</small></button><button id="startQuick"><span>👑</span><strong>QUICK RESCUE</strong><small>2 short stages</small></button></div>';dialog({eyebrow:'WELCOME TO THE DEEP',title:'Save Princess Caspia',text:'An enchanted spell has trapped Caspia. Help Snap pop the bubbles, defeat the guardians, and bring her home!',html:card,picture:'',buttons:[{label:'Level Map',action:levelMap},{label:'Boss Demo',action:()=>{enterStage('demo',4)}},{label:'How to Play',action:()=>guide('welcome')}]});$('startAdventure').onclick=()=>{initialize('story',progress.unlocked);beginAdventure()};$('startQuick').onclick=()=>{initialize('quick',1,0);beginAdventure()}}
function beginAdventure(){let seen=false;try{seen=localStorage.getItem(GUIDE)==='yes'}catch{}if(!seen&&state.level===1&&state.quickStage===0){guide(false)}else closeDialog()}
function guide(fromPause){const steps=[{title:'Meet Snap!',text:'Snap is Caspia’s royal pistol shrimp. His oversized claw launches glowing bubbles to free the princess.'},{title:'Aim and Shoot',text:'Drag your finger on the board to aim. Release to shoot! Match 3 or more bubbles of the same color.'},{title:'Swap Your Bubbles',text:'Look at READY and NEXT. Tap SWAP to exchange them without using a shot. Use the best color for your target.'}];let i=0;function page(){const s=steps[i];const art=i===0?'<div class="tutorial-art tutorial-snap" id="snapDemo"></div>':i===1?'<div class="tutorial-art"><span class="tutorial-bubble"></span><span class="tutorial-bubble blue"></span><span class="tutorial-bubble blue"></span><span class="tutorial-bubble blue"></span><div class="tutorial-arrow">⋰ ⋰ ⋰ ↑</div></div>':'<div class="tutorial-art"><span class="tutorial-bubble pink"></span><span class="swap-illustration">⇄</span><span class="tutorial-bubble blue"></span></div>';dialog({eyebrow:`HOW TO PLAY · ${i+1} / 3`,title:s.title,text:s.text,html:art,buttons:[{label:'Skip',action:()=>finishGuide(true)},{label:i===steps.length-1?'Practice!':'Next →',kind:'primary',action:()=>{if(++i<steps.length)page();else finishGuide(false)}}]});if(i===0){const svg=els.snap.querySelector('svg').cloneNode(true);$('snapDemo').appendChild(svg)}}function finishGuide(skip){try{localStorage.setItem(GUIDE,'yes')}catch{}if(fromPause==='welcome'){welcome();return}if(fromPause){pauseDialog();return}closeDialog();if(!skip&&state.playing){state.tutorial='shoot';setTip('PRACTICE: Drag to aim and release to pop 3 matching bubbles!');setHint('Practice your first shot • timer paused')}else state.tutorial=''}page()}
function aimPoint(e){const rect=els.canvas.getBoundingClientRect();const scaleX=state.w/rect.width,scaleY=state.h/rect.height;state.aim.x=(e.clientX-rect.left)*scaleX;state.aim.y=(e.clientY-rect.top)*scaleY;els.snap.classList.toggle('aim-left',state.aim.x<state.w*.35);els.snap.classList.toggle('aim-right',state.aim.x>state.w*.65);const direction=(state.aim.x-state.w/2)/state.w;const claw=els.snap.querySelector('#clawGroup');if(claw)claw.style.transform='rotate('+Math.max(-18,Math.min(18,-direction*48))+'deg)'}
els.canvas.addEventListener('pointerdown',e=>{if(state.modal||state.paused&&!state.tutorial||!state.playing)return;pointerDown=true;try{els.canvas.setPointerCapture(e.pointerId)}catch{}aimPoint(e)});
els.canvas.addEventListener('pointermove',e=>{if(pointerDown||(e.pointerType==='mouse'&&state.playing&&!state.modal))aimPoint(e)});
els.canvas.addEventListener('pointerup',e=>{if(!pointerDown)return;pointerDown=false;aimPoint(e);launch()});els.canvas.addEventListener('pointercancel',()=>pointerDown=false);
els.canvas.addEventListener('keydown',e=>{if(e.key==='ArrowLeft'){state.aim.x-=16;e.preventDefault()}else if(e.key==='ArrowRight'){state.aim.x+=16;e.preventDefault()}else if(e.code==='Space'||e.key==='Enter'){e.preventDefault();launch()}});
$('swapBtn').addEventListener('click',()=>{if(!state.playing||state.modal||state.shot||state.boss?.exposed)return;if(state.paused&&state.tutorial!=='swap')return;[state.ready,state.next]=[state.next,state.ready];paintAmmo();sfx('swap');if(state.tutorial==='swap'){state.tutorial='';setTip('');setHint('Great! The rescue has begun.');last=performance.now()}});
$('desktopMapBtn').onclick=levelMap;$('guideBtn').onclick=()=>guide(true);$('mapBtn').onclick=levelMap;$('pauseBtn').onclick=()=>{if(state.playing)pauseDialog();else welcome()};$('soundBtn').onclick=()=>{soundEnabled=!soundEnabled;$('soundBtn').textContent=soundEnabled?'♫':'♪';$('soundBtn').setAttribute('aria-label',soundEnabled?'Mute sound':'Unmute sound');if(soundEnabled)sfx('click')};$('retryInit').onclick=()=>initialize(state.mode,state.level,state.quickStage);$('backLink').addEventListener('click',e=>{if(state.playing){e.preventDefault();ask('Return to the portal?','Your completed levels stay saved. The current round will end.',()=>location.href='index.html',()=>state.playing?pauseDialog():welcome())}});
document.addEventListener('keydown',e=>{if(e.code==='Space'&&state.playing&&!state.modal&&!['BUTTON','A'].includes(document.activeElement.tagName)){e.preventDefault();launch()}else if(e.key==='Escape'&&state.playing&&!state.modal){pauseDialog();e.preventDefault()}else if((e.key==='s'||e.key==='S')&&state.playing&&!state.modal&&!state.shot){$('swapBtn').click()}});
document.addEventListener('visibilitychange',()=>{if(document.hidden&&state.playing&&!state.modal){pauseDialog()}});
window.addEventListener('resize',()=>{if(!state.started)return;fit();render()});
function frame(now){const dt=Math.min(.045,Math.max(0,(now-last)/1000||0));last=now;try{if(state.tutorial==='shoot'||state.tutorial==='swap'){state.paused=false;const s=state.seconds;step(dt);state.seconds=s}else step(dt);render()}catch(e){showError(e)}raf=requestAnimationFrame(frame)}
try{initialize('story',1);const hash=location.hash.slice(1);if(hash==='quick'){initialize('quick',1,0);beginAdventure()}else if(hash==='demo'){enterStage('demo',4)}else welcome();last=performance.now();raf=requestAnimationFrame(frame)}catch(e){showError(e)}
})();
